export default data = [
  {
    id: 1,
    img: require('../product/img/android.png'),
    title: 'OPPO A54 128 GB (Starry Blue, 6 GB RAM)',
    price: '₹1,499.00/ Month',
  },
  {
    id: 2,
    img: require('../product/img/briefcase.png'),
    title: 'CAVALO - Be Unique Hand Pouch. Do...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 3,
    img: require('../product/img/cap.png'),
    title: 'MERCHANT ANCHOR CAP...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 4,
    img: require('../product/img/gym.png'),
    title: 'Sketra Neo Run Treadmill',
    price: '₹1,499.00/ Month',
  },
  {
    id: 5,
    img: require('../product/img/iphone.png'),
    title: 'APPLE iPhone 13 (Starlight, 128 GB)',
    price: '₹1,499.00/ Month',
  },
  {
    id: 6,
    img: require('../product/img/saree.png'),
    title: 'Neutral Beige Kurta with Handprint...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 7,
    img: require('../product/img/towel.png'),
    title: 'SOFTSPUN Microfiber Cloth - 4 pcs',
    price: '₹1,499.00/ Month',
  },
  {
    id: 8,
    img: require('../product/img/washing-machine.jpg'),
    title: 'Semi Automatic Washing Machine',
    price: '₹1,499.00/ Month',
  },
  {
    id: 9,
    img: require('../product/img/android.png'),
    title: 'OPPO A54 128 GB (Starry Blue, 6 GB RAM)',
    price: '₹1,499.00/ Month',
  },
  {
    id: 10,
    img: require('../product/img/briefcase.png'),
    title: 'CAVALO - Be Unique Hand Pouch. Do...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 11,
    img: require('../product/img/cap.png'),
    title: 'MERCHANT ANCHOR CAP...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 12,
    img: require('../product/img/gym.png'),
    title: 'Sketra Neo Run Treadmill',
    price: '₹1,499.00/ Month',
  },
  {
    id: 13,
    img: require('../product/img/android.png'),
    title: 'OPPO A54 128 GB (Starry Blue, 6 GB RAM)',
    price: '₹1,499.00/ Month',
  },
  {
    id: 14,
    img: require('../product/img/briefcase.png'),
    title: 'CAVALO - Be Unique Hand Pouch. Do...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 15,
    img: require('../product/img/cap.png'),
    title: 'MERCHANT ANCHOR CAP...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 16,
    img: require('../product/img/gym.png'),
    title: 'Sketra Neo Run Treadmill',
    price: '₹1,499.00/ Month',
  },
  {
    id: 17,
    img: require('../product/img/android.png'),
    title: 'OPPO A54 128 GB (Starry Blue, 6 GB RAM)',
    price: '₹1,499.00/ Month',
  },
  {
    id: 18,
    img: require('../product/img/briefcase.png'),
    title: 'CAVALO - Be Unique Hand Pouch. Do...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 19,
    img: require('../product/img/cap.png'),
    title: 'MERCHANT ANCHOR CAP...',
    price: '₹1,499.00/ Month',
  },
  {
    id: 20,
    img: require('../product/img/gym.png'),
    title: 'Sketra Neo Run Treadmill',
    price: '₹1,499.00/ Month',
  },
];
